/**
 * @missionhud/appspec-provenance
 *
 * Helpers for the per-node `_provenance` envelope every AppSpec node
 * carries — Project, Screen, ComponentInstance, AssetRef, Flow, FlowStep.
 * The envelope is W3C PROV-shaped so it interoperates with the broader
 * compliance / audit-trail ecosystem.
 *
 * Source kinds (see canonical schema `$defs/SourceKind`):
 *   human-edit       — user-driven mutation in a producer UI
 *   figma-import     — extracted from a Figma file
 *   mhb-push         — proposed/applied by Mission HUD Builder
 *   mockingbird-ai   — generated by Mission HUD Designer's orchestrator
 *                      (the 'mockingbird-ai' name is retained for
 *                      back-compat with pre-rename specs in the wild;
 *                      a future v11 will deprecate in favour of
 *                      'designer-ai')
 *   preset-load      — loaded from a curated preset
 *   unknown          — legacy / migrated, source not recorded
 */

'use strict';

const crypto = require('crypto');

const VALID_SOURCES = new Set([
  'human-edit',
  'figma-import',
  'mhb-push',
  'mockingbird-ai',
  'preset-load',
  'unknown',
]);

const VALID_ID_KINDS = new Set(['proj', 'screen', 'comp', 'flow', 'step']);

function nowIso() {
  return new Date().toISOString();
}

function assertSource(source) {
  if (!VALID_SOURCES.has(source)) {
    throw new Error(`Provenance source must be one of ${[...VALID_SOURCES].join(', ')} — got: ${source}`);
  }
}

/**
 * Create a fresh Provenance envelope. Used at node-creation time.
 *
 * @param {object} opts
 * @param {string} opts.source - one of VALID_SOURCES
 * @param {string} [opts.at] - ISO timestamp; defaults to now
 * @param {string} [opts.note] - optional first-timeline-entry note
 * @param {string} [opts.figmaNodeId]
 * @param {string} [opts.mhbId]
 * @returns {object} a Provenance envelope per the AppSpec v10 schema
 */
function createProvenance({ source, at, note, figmaNodeId, mhbId } = {}) {
  assertSource(source);
  const ts = at || nowIso();
  return {
    createdBy: source,
    createdAt: ts,
    lastEditedBy: source,
    lastEditedAt: ts,
    figmaNodeId: figmaNodeId || null,
    figmaNodeIdHistory: figmaNodeId ? [figmaNodeId] : [],
    mhbId: mhbId || null,
    mhbIdHistory: mhbId ? [mhbId] : [],
    sourceTimeline: [{ source, at: ts, ...(note ? { note } : {}) }],
    _tombstone: null,
  };
}

/**
 * Update an existing Provenance envelope for an edit. Appends a
 * timeline entry (audit trail) and bumps lastEditedBy/At.
 *
 * Idempotent on no-op edits — if source + at + note match the most
 * recent timeline entry exactly, skip the append. This prevents
 * audit spam from tools that touch every node on every read.
 *
 * Returns the envelope (mutated in place) or a fresh one if `p` was
 * null/invalid.
 */
function touchProvenance(p, { source, at, note } = {}) {
  assertSource(source);
  if (!p || typeof p !== 'object') {
    return createProvenance({ source, at, note });
  }
  const ts = at || nowIso();
  const last = (p.sourceTimeline || [])[p.sourceTimeline?.length - 1];
  const sameEntry = last && last.source === source && last.at === ts && last.note === note;
  if (!sameEntry) {
    p.sourceTimeline = p.sourceTimeline || [];
    p.sourceTimeline.push({ source, at: ts, ...(note ? { note } : {}) });
  }
  p.lastEditedBy = source;
  p.lastEditedAt = ts;
  return p;
}

/**
 * Set / replace an external ID (figmaNodeId, mhbId). The old value, if
 * any, is pushed to <kind>History so renames are traceable. Setting null
 * clears the current ID but preserves history.
 *
 * @param {object} p - the provenance envelope
 * @param {'figma'|'mhb'} kind - which external ID slot
 * @param {string|null} id - the new value, or null to clear
 */
function setExternalId(p, kind, id) {
  if (!p || typeof p !== 'object') return p;
  const idField = kind === 'figma' ? 'figmaNodeId' : kind === 'mhb' ? 'mhbId' : null;
  const histField = kind === 'figma' ? 'figmaNodeIdHistory' : kind === 'mhb' ? 'mhbIdHistory' : null;
  if (!idField) throw new Error(`Unknown external ID kind: ${kind}`);
  const prev = p[idField];
  if (prev && prev !== id) {
    p[histField] = p[histField] || [];
    if (!p[histField].includes(prev)) p[histField].push(prev);
  }
  if (id) {
    p[histField] = p[histField] || [];
    if (!p[histField].includes(id)) p[histField].push(id);
  }
  p[idField] = id;
  return p;
}

/**
 * Soft-delete: mark a node as removed-from-external-source but keep it
 * in the AppSpec for human review. Consumer UIs surface tombstones for
 * resolution (delete / restore / convert).
 *
 * @param {object} p
 * @param {object} opts
 * @param {'figma'|'mhb'} opts.removedFrom
 * @param {string} [opts.at]
 * @param {string} [opts.lastSeenAt]
 */
function markTombstone(p, { removedFrom, at, lastSeenAt } = {}) {
  if (!p || typeof p !== 'object') return p;
  if (removedFrom !== 'figma' && removedFrom !== 'mhb') {
    throw new Error(`Tombstone removedFrom must be 'figma' or 'mhb' — got: ${removedFrom}`);
  }
  p._tombstone = {
    removedFrom,
    at: at || nowIso(),
    lastSeenAt: lastSeenAt || null,
    humanReviewed: false,
  };
  return p;
}

/**
 * Resolve a tombstone with a human decision. `restore` clears the
 * tombstone; `delete` and `convert` mark it humanReviewed for downstream
 * processing.
 *
 * @param {'delete'|'restore'|'convert'} decision
 * @param {string} [note]
 */
function resolveTombstone(p, decision, note) {
  if (!p || !p._tombstone) return p;
  if (!['delete', 'restore', 'convert'].includes(decision)) {
    throw new Error(`Tombstone decision must be 'delete', 'restore', or 'convert' — got: ${decision}`);
  }
  if (decision === 'restore') {
    p._tombstone = null;
    return p;
  }
  p._tombstone.humanReviewed = true;
  p._tombstone.humanDecision = decision;
  p._tombstone.humanDecisionAt = nowIso();
  if (note) p._tombstone.humanDecisionNote = note;
  return p;
}

/**
 * Generate a v10-style internal entity ID with the right kind prefix.
 * Format: `<prefix>_<12-hex-chars>`. Random; stable; never collides in
 * practice. Crypto-backed.
 *
 * @param {'proj'|'screen'|'comp'|'flow'|'step'} kind
 * @returns {string}
 */
function generateId(kind) {
  if (!VALID_ID_KINDS.has(kind)) {
    throw new Error(`Unknown id kind: ${kind} (valid: ${[...VALID_ID_KINDS].join(', ')})`);
  }
  // 8 bytes of randomness → 16 hex chars; we take the first 12 for
  // tidy ids that still have ~10^14 keyspace.
  const rand = crypto.randomBytes(8).toString('hex').slice(0, 12);
  return `${kind}_${rand}`;
}

module.exports = {
  VALID_SOURCES,
  VALID_ID_KINDS,
  createProvenance,
  touchProvenance,
  setExternalId,
  markTombstone,
  resolveTombstone,
  generateId,
  nowIso,
};
